networks:
  dev:
    driver: bridge

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - dev

  front:
    build: ./front
    ports:
      - 5173:5173
    depends_on:
      - back
    networks:
      - dev

  back:
    build: ./back
    ports:
      - 3000:3000
    depends_on:
      - nginx
      - redis
      - mongo
    networks:
      - dev

  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    networks:
      - dev

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - dev

volumes:
  redis_data:
  mongo_data:
